// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/google/uuid"
)

type Url struct {
	ID           uuid.UUID
	OriginalUrl  string
	ConvertedUrl string
}
