// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url.sql

package database

import (
	"context"
)

const createMapping = `-- name: CreateMapping :exec
INSERT INTO url (id, original_url, converted_url)
VALUES ($1, $2, $3)
`

type CreateMappingParams struct {
	ID           string
	OriginalUrl  string
	ConvertedUrl string
}

func (q *Queries) CreateMapping(ctx context.Context, arg CreateMappingParams) error {
	_, err := q.db.ExecContext(ctx, createMapping, arg.ID, arg.OriginalUrl, arg.ConvertedUrl)
	return err
}

const getConverted = `-- name: GetConverted :one
SELECT id, original_url, converted_url FROM url WHERE converted_url = $1
`

func (q *Queries) GetConverted(ctx context.Context, convertedUrl string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getConverted, convertedUrl)
	var i Url
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.ConvertedUrl)
	return i, err
}
