// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: url.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const createMapping = `-- name: CreateMapping :exec
INSERT INTO url (id, original_url, converted_url)
VALUES ($1, $2, $3)
`

type CreateMappingParams struct {
	ID           uuid.UUID
	OriginalUrl  string
	ConvertedUrl string
}

func (q *Queries) CreateMapping(ctx context.Context, arg CreateMappingParams) error {
	_, err := q.db.ExecContext(ctx, createMapping, arg.ID, arg.OriginalUrl, arg.ConvertedUrl)
	return err
}

const getAllMappings = `-- name: GetAllMappings :many
SELECT id, original_url, converted_url FROM url
`

func (q *Queries) GetAllMappings(ctx context.Context) ([]Url, error) {
	rows, err := q.db.QueryContext(ctx, getAllMappings)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Url
	for rows.Next() {
		var i Url
		if err := rows.Scan(&i.ID, &i.OriginalUrl, &i.ConvertedUrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConverted = `-- name: GetConverted :one
SELECT id, original_url, converted_url FROM url WHERE converted_url = $1
`

func (q *Queries) GetConverted(ctx context.Context, convertedUrl string) (Url, error) {
	row := q.db.QueryRowContext(ctx, getConverted, convertedUrl)
	var i Url
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.ConvertedUrl)
	return i, err
}
