// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: feeds_follower.sql

package database

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createFeedFollower = `-- name: CreateFeedFollower :one

INSERT INTO feeds_follower (id,created_at,updated_at,user_id,feed_id)
VALUES ($1,$2,$3,$4,$5)
RETURNING id, created_at, updated_at, user_id, feed_id
`

type CreateFeedFollowerParams struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	UserID    uuid.UUID
	FeedID    uuid.UUID
}

func (q *Queries) CreateFeedFollower(ctx context.Context, arg CreateFeedFollowerParams) (FeedsFollower, error) {
	row := q.db.QueryRowContext(ctx, createFeedFollower,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.UserID,
		arg.FeedID,
	)
	var i FeedsFollower
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const deleteFeedFollower = `-- name: DeleteFeedFollower :exec

DELETE FROM feeds_follower WHERE id=$1 and user_id=$2
`

type DeleteFeedFollowerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteFeedFollower(ctx context.Context, arg DeleteFeedFollowerParams) error {
	_, err := q.db.ExecContext(ctx, deleteFeedFollower, arg.ID, arg.UserID)
	return err
}

const existFeedFollower = `-- name: ExistFeedFollower :one
SELECT id, created_at, updated_at, user_id, feed_id FROM feeds_follower WHERE id=$1 and user_id=$2
`

type ExistFeedFollowerParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) ExistFeedFollower(ctx context.Context, arg ExistFeedFollowerParams) (FeedsFollower, error) {
	row := q.db.QueryRowContext(ctx, existFeedFollower, arg.ID, arg.UserID)
	var i FeedsFollower
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}

const getFeedFollower = `-- name: GetFeedFollower :many

SELECT id, created_at, updated_at, user_id, feed_id from feeds_follower WHERE user_id=$1
`

func (q *Queries) GetFeedFollower(ctx context.Context, userID uuid.UUID) ([]FeedsFollower, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollower, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedsFollower
	for rows.Next() {
		var i FeedsFollower
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserID,
			&i.FeedID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
